In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [4]:
df = pd.read_excel('/content/제주특별자치도_버스정류소현황_201708..xlsx')
df

FileNotFoundError: ignored

In [5]:
plt.scatter(df['경도'],df['위도'])

NameError: ignored

In [ ]:
df

        연번      정류소ID       정류소명          경도         위도        위치정보(주변설명)
0        1  406000324   (구)중앙파출소  126.560894  33.247598       윤성현내과의원 건너편
1        2  406000467   (구)중앙파출소  126.560367  33.247000      M-STAY제주호텔 앞
2        3  406001176   (구)중앙파출소  126.560890  33.247515       에이스모텔(후문) 앞
3        4  406001109  1100고지휴게소  126.463076  33.357816     1100고지휴게소 맞은편
4        5  405001361  1100고지휴게소  126.462945  33.357826  1100고지휴게소주차장 좌측끝
...    ...        ...        ...         ...        ...               ...
3341  3342  405001116        흥국사  126.378422  33.452634     납읍방향. 용흥3길 입구
3342  3343  405001115        흥국사  126.378100  33.452446          용흥3길이정표앞
3343  3344  406001056      희진주유소  126.874037  33.377568           희진주유소 앞
3344  3345  406001055      희진주유소  126.873644  33.376610         희진주유소 건너편
3345  3346  405000520       히귀반석  126.407856  33.477556     커민스종합서비수대리점우측

[3346 rows x 6 columns]

In [ ]:
df[df['정류소명'] == '(구)중앙파출소']

   연번      정류소ID      정류소명          경도         위도    위치정보(주변설명)
0   1  406000324  (구)중앙파출소  126.560894  33.247598   윤성현내과의원 건너편
1   2  406000467  (구)중앙파출소  126.560367  33.247000  M-STAY제주호텔 앞
2   3  406001176  (구)중앙파출소  126.560890  33.247515   에이스모텔(후문) 앞

In [ ]:
df

        연번      정류소ID       정류소명          경도         위도        위치정보(주변설명)
0        1  406000324   (구)중앙파출소  126.560894  33.247598       윤성현내과의원 건너편
1        2  406000467   (구)중앙파출소  126.560367  33.247000      M-STAY제주호텔 앞
2        3  406001176   (구)중앙파출소  126.560890  33.247515       에이스모텔(후문) 앞
3        4  406001109  1100고지휴게소  126.463076  33.357816     1100고지휴게소 맞은편
4        5  405001361  1100고지휴게소  126.462945  33.357826  1100고지휴게소주차장 좌측끝
...    ...        ...        ...         ...        ...               ...
3341  3342  405001116        흥국사  126.378422  33.452634     납읍방향. 용흥3길 입구
3342  3343  405001115        흥국사  126.378100  33.452446          용흥3길이정표앞
3343  3344  406001056      희진주유소  126.874037  33.377568           희진주유소 앞
3344  3345  406001055      희진주유소  126.873644  33.376610         희진주유소 건너편
3345  3346  405000520       히귀반석  126.407856  33.477556     커민스종합서비수대리점우측

[3346 rows x 6 columns]

In [ ]:
df.head()
#df.head(20)

   연번      정류소ID       정류소명          경도         위도        위치정보(주변설명)
0   1  406000324   (구)중앙파출소  126.560894  33.247598       윤성현내과의원 건너편
1   2  406000467   (구)중앙파출소  126.560367  33.247000      M-STAY제주호텔 앞
2   3  406001176   (구)중앙파출소  126.560890  33.247515       에이스모텔(후문) 앞
3   4  406001109  1100고지휴게소  126.463076  33.357816     1100고지휴게소 맞은편
4   5  405001361  1100고지휴게소  126.462945  33.357826  1100고지휴게소주차장 좌측끝

In [ ]:
df.tail()

        연번      정류소ID   정류소명          경도         위도     위치정보(주변설명)
3341  3342  405001116    흥국사  126.378422  33.452634  납읍방향. 용흥3길 입구
3342  3343  405001115    흥국사  126.378100  33.452446       용흥3길이정표앞
3343  3344  406001056  희진주유소  126.874037  33.377568        희진주유소 앞
3344  3345  406001055  희진주유소  126.873644  33.376610      희진주유소 건너편
3345  3346  405000520   히귀반석  126.407856  33.477556  커민스종합서비수대리점우측

In [ ]:
df2 = pd.read_excel('/content/제주특별자치도_한라산탐방객현황_2014_2018..xlsx')
df2

           구분    어리목     영실    성판악    관음사   돈내코
0    2014년 1월  38438  23593  63950   7769  2428
1    2014년 2월  26338  26009  39079   4497  1338
2    2014년 3월  25865  15816  29038   2476  1302
3    2014년 4월  36917  21065  33980   4017   997
4    2014년 5월  32995  30804  34533   5813  1681
5    2014년 6월  33041  25526  27411   5570  1938
6    2014년 7월  28586  14744  18647   5039   762
7    2014년 8월  28513  15746  28382   4463   762
8    2014년 9월  33885  22324  31839   6349   667
9   2014년 10월  41932  34724  47012   8965   876
10  2014년 11월  31946  26221  38082   8979   469
11  2014년 12월  35503  16147  26320   3748   346
12   2015년 1월  48351  35139  57484   8635   839
13   2015년 2월  36716  23697  36103   6069   629
14   2015년 3월  36579  20020  25834   4312   432
15   2015년 4월  41783  21595  52223   5118   461
16   2015년 5월  49974  31009  72025   6595  1011
17   2015년 6월  20757  22857  26309   4164   822
18   2015년 7월  12039  14092  21410   5099   413
19   2015년 8월  20464  19327  27303   7127   516
20   2015년 9월  28352  20374  29017   3968   472
21  2015년 10월  48079  44898  49699   6311   568
22  2015년 11월  31063  28792  29851   5612   450
23  2015년 12월  35555  29299  34969   2679   391
24   2016년 1월  41455  22958  58073   2959   579
25   2016년 2월  38633  29337  31659   2343   409
26   2016년 3월  34784  21600  24486   2222   393
27   2016년 4월  32786  19373  27032   2637   500
28   2016년 5월  38241  29043  35252   3364   832
29   2016년 6월  29366  22713  22059   2419  1063
30   2016년 7월  23013  16139  19653   3722   398
31   2016년 8월  27882  20808  20853   4920   573
32   2016년 9월  25478  21522  21227   3228   371
33  2016년 10월  36473  27096  34512   6401   577
34  2016년 11월  27229  30821  28403   5146   694
35  2016년 12월  25695  22778  27339   3799   578
36   2017년 1월  37527  26668  38091   5653   771
37   2017년 2월  26479  18898  40952   4876   432
38   2017년 3월  17566  20526  22304   4635   412
39   2017년 4월  18392  20918  27603   5938   540
40   2017년 5월  30191  34246  35759   7492   910
41   2017년 6월  19528  26566  22292   6862   949
42   2017년 7월  15123  13219  15488   7931   495
43   2017년 8월  16833  13862  16021   6909   567
44   2017년 9월  15134  17796  22478   6194   484
45  2017년 10월  33498  36046  37228  11709   622
46  2017년 11월  23444  25622  39297   7056   574
47  2017년 12월  32035  20515  35675   5176   433
48   2018년 1월  28301  21052  55637   6015   553
49   2018년 2월  12335  11461  16998   6212   231
50   2018년 3월  16864  17166  27623   4246   436
51   2018년 4월  19604  18928  31922   4292   451
52   2018년 5월  25934  29981  34772   6597   626
53   2018년 6월  20919  30555  21485   6880   703
54   2018년 7월  12131  15324   6052  12369   416
55   2018년 8월  15592  17959  17601   6709   406
56   2018년 9월  15534  19359  21581   4289   222
57  2018년 10월  29580  36817  38166   7095   622
58  2018년 11월  21422  25068  28438   7009   342
59  2018년 12월  18264  12957  18035   3494   185

In [ ]:
df2.groupby('어리목').sum()

          영실    성판악    관음사   돈내코
어리목
12039  14092  21410   5099   413
12131  15324   6052  12369   416
12335  11461  16998   6212   231
15123  13219  15488   7931   495
15134  17796  22478   6194   484
15534  19359  21581   4289   222
15592  17959  17601   6709   406
16833  13862  16021   6909   567
16864  17166  27623   4246   436
17566  20526  22304   4635   412
18264  12957  18035   3494   185
18392  20918  27603   5938   540
19528  26566  22292   6862   949
19604  18928  31922   4292   451
20464  19327  27303   7127   516
20757  22857  26309   4164   822
20919  30555  21485   6880   703
21422  25068  28438   7009   342
23013  16139  19653   3722   398
23444  25622  39297   7056   574
25478  21522  21227   3228   371
25695  22778  27339   3799   578
25865  15816  29038   2476  1302
25934  29981  34772   6597   626
26338  26009  39079   4497  1338
26479  18898  40952   4876   432
27229  30821  28403   5146   694
27882  20808  20853   4920   573
28301  21052  55637   6015   553
28352  20374  29017   3968   472
28513  15746  28382   4463   762
28586  14744  18647   5039   762
29366  22713  22059   2419  1063
29580  36817  38166   7095   622
30191  34246  35759   7492   910
31063  28792  29851   5612   450
31946  26221  38082   8979   469
32035  20515  35675   5176   433
32786  19373  27032   2637   500
32995  30804  34533   5813  1681
33041  25526  27411   5570  1938
33498  36046  37228  11709   622
33885  22324  31839   6349   667
34784  21600  24486   2222   393
35503  16147  26320   3748   346
35555  29299  34969   2679   391
36473  27096  34512   6401   577
36579  20020  25834   4312   432
36716  23697  36103   6069   629
36917  21065  33980   4017   997
37527  26668  38091   5653   771
38241  29043  35252   3364   832
38438  23593  63950   7769  2428
38633  29337  31659   2343   409
41455  22958  58073   2959   579
41783  21595  52223   5118   461
41932  34724  47012   8965   876
48079  44898  49699   6311   568
48351  35139  57484   8635   839
49974  31009  72025   6595  1011

In [ ]:
df2

           구분    어리목     영실    성판악    관음사   돈내코
0    2014년 1월  38438  23593  63950   7769  2428
1    2014년 2월  26338  26009  39079   4497  1338
2    2014년 3월  25865  15816  29038   2476  1302
3    2014년 4월  36917  21065  33980   4017   997
4    2014년 5월  32995  30804  34533   5813  1681
5    2014년 6월  33041  25526  27411   5570  1938
6    2014년 7월  28586  14744  18647   5039   762
7    2014년 8월  28513  15746  28382   4463   762
8    2014년 9월  33885  22324  31839   6349   667
9   2014년 10월  41932  34724  47012   8965   876
10  2014년 11월  31946  26221  38082   8979   469
11  2014년 12월  35503  16147  26320   3748   346
12   2015년 1월  48351  35139  57484   8635   839
13   2015년 2월  36716  23697  36103   6069   629
14   2015년 3월  36579  20020  25834   4312   432
15   2015년 4월  41783  21595  52223   5118   461
16   2015년 5월  49974  31009  72025   6595  1011
17   2015년 6월  20757  22857  26309   4164   822
18   2015년 7월  12039  14092  21410   5099   413
19   2015년 8월  20464  19327  27303   7127   516
20   2015년 9월  28352  20374  29017   3968   472
21  2015년 10월  48079  44898  49699   6311   568
22  2015년 11월  31063  28792  29851   5612   450
23  2015년 12월  35555  29299  34969   2679   391
24   2016년 1월  41455  22958  58073   2959   579
25   2016년 2월  38633  29337  31659   2343   409
26   2016년 3월  34784  21600  24486   2222   393
27   2016년 4월  32786  19373  27032   2637   500
28   2016년 5월  38241  29043  35252   3364   832
29   2016년 6월  29366  22713  22059   2419  1063
30   2016년 7월  23013  16139  19653   3722   398
31   2016년 8월  27882  20808  20853   4920   573
32   2016년 9월  25478  21522  21227   3228   371
33  2016년 10월  36473  27096  34512   6401   577
34  2016년 11월  27229  30821  28403   5146   694
35  2016년 12월  25695  22778  27339   3799   578
36   2017년 1월  37527  26668  38091   5653   771
37   2017년 2월  26479  18898  40952   4876   432
38   2017년 3월  17566  20526  22304   4635   412
39   2017년 4월  18392  20918  27603   5938   540
40   2017년 5월  30191  34246  35759   7492   910
41   2017년 6월  19528  26566  22292   6862   949
42   2017년 7월  15123  13219  15488   7931   495
43   2017년 8월  16833  13862  16021   6909   567
44   2017년 9월  15134  17796  22478   6194   484
45  2017년 10월  33498  36046  37228  11709   622
46  2017년 11월  23444  25622  39297   7056   574
47  2017년 12월  32035  20515  35675   5176   433
48   2018년 1월  28301  21052  55637   6015   553
49   2018년 2월  12335  11461  16998   6212   231
50   2018년 3월  16864  17166  27623   4246   436
51   2018년 4월  19604  18928  31922   4292   451
52   2018년 5월  25934  29981  34772   6597   626
53   2018년 6월  20919  30555  21485   6880   703
54   2018년 7월  12131  15324   6052  12369   416
55   2018년 8월  15592  17959  17601   6709   406
56   2018년 9월  15534  19359  21581   4289   222
57  2018년 10월  29580  36817  38166   7095   622
58  2018년 11월  21422  25068  28438   7009   342
59  2018년 12월  18264  12957  18035   3494   185

In [ ]:
df2['어리목'].sum()

1706936

In [ ]:
df2

           구분    어리목     영실    성판악    관음사   돈내코
0    2014년 1월  38438  23593  63950   7769  2428
1    2014년 2월  26338  26009  39079   4497  1338
2    2014년 3월  25865  15816  29038   2476  1302
3    2014년 4월  36917  21065  33980   4017   997
4    2014년 5월  32995  30804  34533   5813  1681
5    2014년 6월  33041  25526  27411   5570  1938
6    2014년 7월  28586  14744  18647   5039   762
7    2014년 8월  28513  15746  28382   4463   762
8    2014년 9월  33885  22324  31839   6349   667
9   2014년 10월  41932  34724  47012   8965   876
10  2014년 11월  31946  26221  38082   8979   469
11  2014년 12월  35503  16147  26320   3748   346
12   2015년 1월  48351  35139  57484   8635   839
13   2015년 2월  36716  23697  36103   6069   629
14   2015년 3월  36579  20020  25834   4312   432
15   2015년 4월  41783  21595  52223   5118   461
16   2015년 5월  49974  31009  72025   6595  1011
17   2015년 6월  20757  22857  26309   4164   822
18   2015년 7월  12039  14092  21410   5099   413
19   2015년 8월  20464  19327  27303   7127   516
20   2015년 9월  28352  20374  29017   3968   472
21  2015년 10월  48079  44898  49699   6311   568
22  2015년 11월  31063  28792  29851   5612   450
23  2015년 12월  35555  29299  34969   2679   391
24   2016년 1월  41455  22958  58073   2959   579
25   2016년 2월  38633  29337  31659   2343   409
26   2016년 3월  34784  21600  24486   2222   393
27   2016년 4월  32786  19373  27032   2637   500
28   2016년 5월  38241  29043  35252   3364   832
29   2016년 6월  29366  22713  22059   2419  1063
30   2016년 7월  23013  16139  19653   3722   398
31   2016년 8월  27882  20808  20853   4920   573
32   2016년 9월  25478  21522  21227   3228   371
33  2016년 10월  36473  27096  34512   6401   577
34  2016년 11월  27229  30821  28403   5146   694
35  2016년 12월  25695  22778  27339   3799   578
36   2017년 1월  37527  26668  38091   5653   771
37   2017년 2월  26479  18898  40952   4876   432
38   2017년 3월  17566  20526  22304   4635   412
39   2017년 4월  18392  20918  27603   5938   540
40   2017년 5월  30191  34246  35759   7492   910
41   2017년 6월  19528  26566  22292   6862   949
42   2017년 7월  15123  13219  15488   7931   495
43   2017년 8월  16833  13862  16021   6909   567
44   2017년 9월  15134  17796  22478   6194   484
45  2017년 10월  33498  36046  37228  11709   622
46  2017년 11월  23444  25622  39297   7056   574
47  2017년 12월  32035  20515  35675   5176   433
48   2018년 1월  28301  21052  55637   6015   553
49   2018년 2월  12335  11461  16998   6212   231
50   2018년 3월  16864  17166  27623   4246   436
51   2018년 4월  19604  18928  31922   4292   451
52   2018년 5월  25934  29981  34772   6597   626
53   2018년 6월  20919  30555  21485   6880   703
54   2018년 7월  12131  15324   6052  12369   416
55   2018년 8월  15592  17959  17601   6709   406
56   2018년 9월  15534  19359  21581   4289   222
57  2018년 10월  29580  36817  38166   7095   622
58  2018년 11월  21422  25068  28438   7009   342
59  2018년 12월  18264  12957  18035   3494   185

In [ ]:
df2['총합'] = 0

In [ ]:
df2.drop('구분',axis = 1,inplace = True)

In [ ]:

for i in range(60):
  df2['총합'].iloc[i] = df2.iloc[i].sum()

In [1]:
df2 = pd.read_excel('/content/제주특별자치도_한라산탐방객현황_2014_2018..xlsx')
df2.loc[60] = 0 
df2['구분'].loc[60] = '2020년 8월 29일'
list = ['어리목', '영실', '성판악', '관음사', '돈내코']
for i in list:
    df2[i].loc[60] = df2[i].sum()

NameError: ignored

In [2]:
df3 = pd.read_csv('/content/hadoop.csv')
df3

NameError: ignored

In [ ]:
len(df3['access_ip'].unique())

51387

In [ ]:
unique_ip = df3['access_ip'].unique().tolist()

In [ ]:
unique_dict = dict.fromkeys(unique_ip)
for i in unique_dict.keys():
  unique_dict[i] = []

In [ ]:
unique_dict

{'188.244.165.181': [],
 '210.54.66.88': [],
 '62.47.31.96': [],
 '88.189.204.99': [],
 '95.90.201.200': [],
 '49.201.126.23': [],
 '157.168.67.74': [],
 '15.11.67.191': [],
 '168.99.244.65': [],
 '111.119.37.132': [],
 '133.52.121.101': [],
 '126.14.177.153': [],
 '230.138.77.239': [],
 '171.15.67.113': [],
 '93.14.188.153': [],
 '188.239.6.244': [],
 '81.132.153.16': [],
 '51.191.56.15': [],
 '173.84.1.90': [],
 '171.114.250.159': [],
 '250.246.163.62': [],
 '206.213.45.105': [],
 '231.221.165.131': [],
 '80.220.81.130': [],
 '247.186.139.68': [],
 '66.53.155.177': [],
 '168.242.88.161': [],
 '67.91.33.53': [],
 '190.228.111.194': [],
 '70.176.195.224': [],
 '151.70.81.166': [],
 '93.123.26.60': [],
 '185.233.145.141': [],
 '164.79.221.159': [],
 '224.248.72.113': [],
 '44.73.35.220': [],
 '66.38.131.229': [],
 '120.40.165.23': [],
 '246.120.161.84': [],
 '161.58.55.147': [],
 '101.197.39.230': [],
 '90.180.218.183': [],
 '155.196.183.11': [],
 '132.115.243.217': [],
 '49.236.36.27': [],
 '220.151.216.249': [],
 '44.106.190.112': [],
 '214.255.249.181': [],
 '32.166.145.248': [],
 '241.170.94.32': [],
 '234.163.238.92': [],
 '39.190.153.105': [],
 '117.188.181.15': [],
 '230.48.19.112': [],
 '89.14.85.7': [],
 '243.43.153.46': [],
 '197.198.238.56': [],
 '20.160.153.225': [],
 '162.123.243.249': [],
 '135.61.128.161': [],
 '11.235.76.148': [],
 '21.73.233.49': [],
 '214.77.46.116': [],
 '8.22.209.166': [],
 '12.49.240.44': [],
 '125.78.212.88': [],
 '208.244.132.250': [],
 '85.103.40.11': [],
 '110.248.165.6': [],
 '209.201.156.174': [],
 '239.123.247.146': [],
 '23.8.205.97': [],
 '14.18.168.39': [],
 '176.50.8.247': [],
 '65.57.103.96': [],
 '136.107.181.163': [],
 '73.195.149.131': [],
 '217.229.146.86': [],
 '249.75.144.119': [],
 '209.193.243.40': [],
 '17.160.68.184': [],
 '131.228.174.222': [],
 '144.121.154.168': [],
 '250.119.12.161': [],
 '228.83.161.39': [],
 '31.157.178.131': [],
 '113.249.44.112': [],
 '253.96.236.138': [],
 '64.113.173.16': [],
 '98.170.94.131': [],
 '52.118.34.206': [],
 '113.25.253.86': [],
 '163.124.95.53': [],
 '153.238.28.13': [],
 '223.25.41.155': [],
 '151.92.115.165': [],
 '55.244.103.55': [],
 '51.182.49.143': [],
 '161.57.82.86': [],
 '176.182.145.81': [],
 '251.78.225.90': [],
 '103.10.170.62': [],
 '203.95.2.4': [],
 '190.104.178.215': [],
 '61.3.214.246': [],
 '60.105.159.168': [],
 '185.142.61.227': [],
 '128.223.237.224': [],
 '252.196.238.172': [],
 '98.18.240.246': [],
 '31.67.54.108': [],
 '250.215.67.118': [],
 '115.226.146.84': [],
 '187.47.143.66': [],
 '36.228.233.154': [],
 '24.111.150.63': [],
 '165.232.49.150': [],
 '28.118.202.48': [],
 '194.1.113.37': [],
 '78.74.233.102': [],
 '1.169.12.32': [],
 '83.58.116.110': [],
 '185.250.168.83': [],
 '27.92.244.225': [],
 '170.182.101.148': [],
 '237.232.110.79': [],
 '225.10.230.230': [],
 '255.66.85.98': [],
 '105.16.52.1': [],
 '231.3.53.178': [],
 '15.33.211.28': [],
 '29.14.183.141': [],
 '95.234.81.31': [],
 '110.131.48.101': [],
 '226.148.73.176': [],
 '157.164.105.153': [],
 '137.31.125.250': [],
 '97.228.137.32': [],
 '142.188.89.124': [],
 '69.39.130.169': [],
 '93.83.224.163': [],
 '211.226.95.210': [],
 '199.225.125.232': [],
 '7.36.65.35': [],
 '225.104.154.11': [],
 '115.252.93.99': [],
 '145.13.124.197': [],
 '158.193.156.107': [],
 '33.192.219.238': [],
 '86.113.127.35': [],
 '15.105.199.23': [],
 '197.222.156.173': [],
 '220.128.153.42': [],
 '184.23.102.89': [],
 '60.251.186.138': [],
 '12.118.16.74': [],
 '123.163.219.234': [],
 '109.95.166.200': [],
 '145.139.28.213': [],
 '68.88.170.247': [],
 '191.183.10.218': [],
 '106.95.186.228': [],
 '160.233.132.93': [],
 '40.211.199.60': [],
 '153.3.229.174': [],
 '136.80.216.125': [],
 '124.138.175.139': [],
 '38.237.242.175': [],
 '52.5.110.61': [],
 '179.50.216.54': [],
 '8.203.4.12': [],
 '238.210.194.228': [],
 '241.50.149.178': [],
 '45.226.142.29': [],
 '187.229.133.247': [],
 '141.20.239.62': [],
 '160.99.246.3': [],
 '43.69.217.131': [],
 '110.125.18.170': [],
 '211.219.225.94': [],
 '57.101.81.138': [],
 '238.67.79.175': [],
 '148.136.207.90': [],
 '182.140.203.100': [],
 '118.109.190.193': [],
 '189.89.47.163': [],
 '242.130.235.154': [],
 '45.105.134.183': [],
 '153.200.76.231': [],
 '7.1.202.174': [],
 '117.239.149.130': [],
 '151.191.177.118': [],
 '146.42.179.242': [],
 '206.79.117.132': [],
 '244.135.199.8': [],
 '67.154.111.86': [],
 '65.168.202.15': [],
 '27.226.143.19': [],
 '252.100.46.182': [],
 '40.49.75.118': [],
 '69.153.59.35': [],
 '174.72.224.133': [],
 '196.241.214.75': [],
 '162.119.110.178': [],
 '88.168.129.79': [],
 '131.63.15.140': [],
 '246.221.45.5': [],
 '12.165.115.93': [],
 '38.200.183.245': [],
 '87.214.65.34': [],
 '13.28.182.217': [],
 '245.248.173.97': [],
 '137.152.10.147': [],
 '130.177.226.121': [],
 '119.112.9.109': [],
 '59.177.188.14': [],
 '168.191.143.134': [],
 '207.213.114.32': [],
 '239.209.83.35': [],
 '101.26.150.126': [],
 '100.83.10.241': [],
 '15.208.226.11': [],
 '237.94.135.157': [],
 '35.115.161.12': [],
 '168.202.233.34': [],
 '122.214.16.34': [],
 '63.3.93.216': [],
 '151.177.190.139': [],
 '32.141.241.23': [],
 '110.239.4.38': [],
 '223.221.125.218': [],
 '112.106.204.115': [],
 '14.29.39.152': [],
 '139.15.195.209': [],
 '151.105.153.25': [],
 '30.150.192.137': [],
 '180.167.121.168': [],
 '190.134.56.54': [],
 '120.149.228.201': [],
 '227.49.102.120': [],
 '65.9.122.1': [],
 '115.254.75.57': [],
 '64.184.203.109': [],
 '209.183.177.234': [],
 '130.250.138.100': [],
 '39.42.206.208': [],
 '113.64.101.26': [],
 '61.217.11.207': [],
 '106.241.177.35': [],
 '75.209.134.221': [],
 '186.150.12.113': [],
 '158.89.56.169': [],
 '141.226.68.42': [],
 '41.67.62.54': [],
 '75.120.120.195': [],
 '39.156.217.230': [],
 '94.51.55.229': [],
 '143.243.246.127': [],
 '248.235.252.116': [],
 '68.160.234.251': [],
 '68.236.251.104': [],
 '255.137.223.210': [],
 '170.5.221.83': [],
 '168.118.140.203': [],
 '164.173.222.41': [],
 '98.78.123.188': [],
 '90.114.126.44': [],
 '218.205.92.96': [],
 '207.134.190.99': [],
 '193.218.185.48': [],
 '119.166.23.198': [],
 '50.59.8.255': [],
 '31.41.9.154': [],
 '38.43.31.31': [],
 '234.56.33.51': [],
 '193.61.117.66': [],
 '157.245.72.62': [],
 '96.217.216.55': [],
 '109.214.61.112': [],
 '78.41.207.45': [],
 '147.34.199.13': [],
 '84.33.20.149': [],
 '124.58.198.178': [],
 '54.195.148.117': [],
 '75.205.193.204': [],
 '196.105.42.103': [],
 '13.8.214.242': [],
 '70.79.198.101': [],
 '157.45.245.201': [],
 '185.92.120.204': [],
 '187.62.219.94': [],
 '241.145.10.79': [],
 '39.223.194.123': [],
 '75.68.207.119': [],
 '49.153.92.30': [],
 '249.93.35.140': [],
 '208.154.206.231': [],
 '6.60.21.31': [],
 '37.215.168.80': [],
 '250.115.202.130': [],
 '19.61.188.75': [],
 '123.88.234.192': [],
 '87.177.17.199': [],
 '181.164.174.154': [],
 '144.151.127.67': [],
 '188.253.24.95': [],
 '235.60.87.89': [],
 '108.167.41.85': [],
 '189.205.115.35': [],
 '116.179.228.51': [],
 '233.203.150.212': [],
 '125.65.85.185': [],
 '125.205.180.79': [],
 '77.97.48.6': [],
 '131.210.62.252': [],
 '9.197.249.250': [],
 '123.215.133.14': [],
 '242.137.84.221': [],
 '223.126.231.118': [],
 '118.47.138.180': [],
 '254.195.87.80': [],
 '94.101.64.123': [],
 '221.12.1.2': [],
 '66.224.145.95': [],
 '3.96.107.173': [],
 '115.86.252.41': [],
 '152.248.130.44': [],
 '134.115.108.245': [],
 '185.51.153.203': [],
 '4.9.189.205': [],
 '155.230.119.187': [],
 '79.89.47.219': [],
 '204.79.52.45': [],
 '233.193.43.107': [],
 '21.87.199.235': [],
 '31.213.255.157': [],
 '5.106.202.30': [],
 '241.178.161.87': [],
 '5.76.119.246': [],
 '115.90.235.202': [],
 '18.204.134.253': [],
 '212.238.66.180': [],
 '179.189.110.132': [],
 '241.188.32.190': [],
 '38.237.233.87': [],
 '162.165.176.13': [],
 '153.20.156.223': [],
 '106.129.176.53': [],
 '86.231.176.16': [],
 '226.102.57.156': [],
 '68.177.147.173': [],
 '85.193.247.232': [],
 '87.58.196.33': [],
 '254.198.217.5': [],
 '53.37.166.148': [],
 '243.183.76.209': [],
 '90.49.20.93': [],
 '203.207.89.129': [],
 '211.163.174.188': [],
 '229.54.47.27': [],
 '130.195.2.50': [],
 '81.227.220.136': [],
 '203.245.251.163': [],
 '6.203.61.121': [],
 '171.108.174.213': [],
 '237.194.123.181': [],
 '223.218.207.70': [],
 '82.185.56.229': [],
 '124.37.16.133': [],
 '178.150.39.12': [],
 '28.157.96.108': [],
 '15.212.249.35': [],
 '193.50.236.93': [],
 '246.84.53.255': [],
 '222.48.45.57': [],
 '120.116.240.85': [],
 '92.106.121.75': [],
 '166.245.49.54': [],
 '241.237.81.4': [],
 '90.28.187.136': [],
 '4.200.221.60': [],
 '35.89.135.231': [],
 '159.68.108.158': [],
 '35.51.133.73': [],
 '180.49.176.191': [],
 '180.18.154.39': [],
 '40.74.25.160': [],
 '176.198.171.73': [],
 '167.184.148.81': [],
 '57.64.145.244': [],
 '76.36.90.172': [],
 '57.150.206.67': [],
 '111.187.34.41': [],
 '133.177.142.171': [],
 '157.218.68.228': [],
 '241.35.92.142': [],
 '131.148.144.183': [],
 '188.72.110.230': [],
 '77.141.181.96': [],
 '122.159.223.47': [],
 '117.17.142.134': [],
 '114.146.158.200': [],
 '11.58.235.237': [],
 '162.153.160.145': [],
 '124.98.30.148': [],
 '8.231.109.6': [],
 '92.100.16.180': [],
 '136.68.36.78': [],
 '28.164.20.11': [],
 '112.135.247.13': [],
 '25.162.56.251': [],
 '103.188.182.181': [],
 '128.214.148.178': [],
 '102.244.246.212': [],
 '132.51.116.71': [],
 '206.210.99.12': [],
 '85.17.35.205': [],
 '22.246.34.18': [],
 '106.50.46.173': [],
 '144.204.128.113': [],
 '117.169.254.132': [],
 '137.78.208.115': [],
 nan: [],
 '174.13.35.119': [],
 '94.171.127.233': [],
 '27.16.109.59': [],
 '197.162.241.43': [],
 '4.189.119.245': [],
 '1.160.176.1': [],
 '210.59.224.63': [],
 '64.197.105.62': [],
 '205.202.243.41': [],
 '59.241.134.231': [],
 '111.52.138.147': [],
 '251.224.30.234': [],
 '178.97.95.31': [],
 '141.188.26.143': [],
 '20.228.91.56': [],
 '171.223.67.25': [],
 '152.72.141.77': [],
 '15.158.186.29': [],
 '75.130.132.7': [],
 '39.69.141.217': [],
 '14.216.7.80': [],
 '52.92.146.172': [],
 '68.78.242.236': [],
 '113.223.161.73': [],
 '45.233.189.237': [],
 '255.252.226.245': [],
 '50.13.140.138': [],
 '186.220.83.163': [],
 '197.7.204.186': [],
 '231.178.69.79': [],
 '155.42.116.157': [],
 '164.48.117.46': [],
 '25.115.146.122': [],
 '90.245.115.248': [],
 '59.44.252.108': [],
 '72.69.213.241': [],
 '24.74.205.227': [],
 '150.183.72.161': [],
 '131.16.22.220': [],
 '5.152.30.244': [],
 '157.203.81.118': [],
 '223.100.13.31': [],
 '19.136.60.72': [],
 '63.216.221.190': [],
 '181.151.245.164': [],
 '129.129.12.123': [],
 '122.65.206.59': [],
 '102.19.201.63': [],
 '46.142.227.182': [],
 '73.4.21.28': [],
 '145.46.72.237': [],
 '234.182.122.238': [],
 '221.209.160.126': [],
 '131.89.169.124': [],
 '253.253.67.43': [],
 '205.9.116.41': [],
 '246.248.246.131': [],
 '255.247.143.74': [],
 '144.214.175.145': [],
 '176.176.167.43': [],
 '190.43.105.185': [],
 '90.176.97.157': [],
 '193.7.119.34': [],
 '41.94.244.113': [],
 '89.182.123.28': [],
 '90.126.53.110': [],
 '238.244.63.94': [],
 '6.251.100.170': [],
 '115.200.18.180': [],
 '19.114.7.124': [],
 '166.126.38.100': [],
 '187.62.111.111': [],
 '91.250.155.109': [],
 '171.191.219.60': [],
 '250.186.148.196': [],
 '66.125.61.10': [],
 '168.42.23.27': [],
 '136.239.189.92': [],
 '119.19.42.162': [],
 '238.196.239.142': [],
 '32.150.151.189': [],
 '227.29.79.141': [],
 '55.134.102.2': [],
 '191.50.107.160': [],
 '113.112.82.90': [],
 '143.129.161.44': [],
 '3.204.37.138': [],
 '167.182.88.104': [],
 '153.166.46.170': [],
 '34.11.3.130': [],
 '62.170.213.209': [],
 '170.96.100.142': [],
 '124.37.58.148': [],
 '29.136.152.74': [],
 '241.58.99.142': [],
 '70.23.5.230': [],
 '33.57.8.8': [],
 '82.87.61.188': [],
 '59.194.12.229': [],
 '188.82.103.253': [],
 '3.69.149.103': [],
 '147.97.161.186': [],
 '139.56.223.94': [],
 '25.25.110.222': [],
 '238.8.206.14': [],
 '148.41.20.133': [],
 '177.158.185.66': [],
 '208.131.59.5': [],
 '212.40.11.26': [],
 '132.230.182.161': [],
 '23.31.244.48': [],
 '38.206.30.23': [],
 '163.80.175.11': [],
 '191.134.189.164': [],
 '179.105.224.245': [],
 '11.84.34.141': [],
 '3.11.159.69': [],
 '9.98.127.249': [],
 '55.36.170.114': [],
 '226.190.224.106': [],
 '32.56.202.66': [],
 '148.6.121.124': [],
 '197.45.13.178': [],
 '100.223.112.188': [],
 '166.193.44.152': [],
 '187.21.122.59': [],
 '14.4.201.55': [],
 '148.176.113.129': [],
 '17.128.168.44': [],
 '174.129.34.107': [],
 '128.180.163.240': [],
 '115.12.84.68': [],
 '226.152.241.214': [],
 '22.135.84.83': [],
 '94.143.99.46': [],
 '5.47.1.204': [],
 '15.121.155.165': [],
 '221.165.146.59': [],
 '56.120.156.34': [],
 '161.245.206.30': [],
 '66.139.108.201': [],
 '103.70.91.144': [],
 '242.113.156.43': [],
 '58.113.53.149': [],
 '56.85.160.68': [],
 '205.23.216.140': [],
 '121.200.92.161': [],
 '124.193.5.133': [],
 '76.155.221.121': [],
 '126.233.29.5': [],
 '106.134.162.188': [],
 '246.81.13.161': [],
 '120.241.69.47': [],
 '146.166.28.68': [],
 '174.251.161.244': [],
 '154.233.6.168': [],
 '40.44.216.103': [],
 '179.160.54.213': [],
 '43.163.250.15': [],
 '4.87.249.41': [],
 '141.29.221.87': [],
 '187.147.234.68': [],
 '137.246.243.78': [],
 '85.19.132.23': [],
 '236.18.221.60': [],
 '166.188.41.216': [],
 '111.237.138.146': [],
 '111.19.221.153': [],
 '81.66.5.204': [],
 '148.165.183.249': [],
 '204.31.71.17': [],
 '140.194.134.189': [],
 '100.236.51.53': [],
 '76.211.218.221': [],
 '153.39.49.237': [],
 '200.247.238.56': [],
 '97.171.109.40': [],
 '99.78.208.62': [],
 '247.225.72.20': [],
 '12.3.176.88': [],
 '76.42.254.13': [],
 '20.62.2.97': [],
 '107.105.163.163': [],
 '249.16.11.215': [],
 '191.11.61.136': [],
 '93.181.177.184': [],
 '123.227.225.28': [],
 '110.203.22.16': [],
 '74.141.12.111': [],
 '223.98.108.147': [],
 '17.234.235.21': [],
 '227.119.193.3': [],
 '97.130.69.90': [],
 '236.188.97.87': [],
 '212.147.189.142': [],
 '248.254.84.118': [],
 '75.184.187.237': [],
 '196.50.29.61': [],
 '248.134.225.136': [],
 '190.10.98.208': [],
 '252.81.82.229': [],
 '185.82.60.15': [],
 '126.165.122.252': [],
 '123.139.175.227': [],
 '83.173.196.126': [],
 '112.63.152.147': [],
 '29.74.164.14': [],
 '252.233.71.249': [],
 '54.118.25.116': [],
 '168.89.56.247': [],
 '125.13.147.120': [],
 '71.135.249.156': [],
 '110.245.194.97': [],
 '51.251.39.94': [],
 '45.231.192.184': [],
 '201.245.196.144': [],
 '165.205.149.85': [],
 '116.53.34.9': [],
 '13.6.171.86': [],
 '61.240.56.214': [],
 '193.117.143.74': [],
 '184.174.18.62': [],
 '107.61.64.145': [],
 '234.177.56.242': [],
 '8.198.219.47': [],
 '145.146.56.36': [],
 '22.175.222.55': [],
 '184.29.117.151': [],
 '34.116.196.188': [],
 '29.25.40.60': [],
 '33.62.186.188': [],
 '99.47.209.244': [],
 '116.45.206.37': [],
 '165.183.219.117': [],
 '41.215.182.198': [],
 '147.128.131.21': [],
 '233.53.71.33': [],
 '19.227.224.145': [],
 '200.182.101.169': [],
 '194.149.143.222': [],
 '67.150.142.43': [],
 '36.137.228.101': [],
 '190.102.245.104': [],
 '42.24.164.9': [],
 '167.150.128.220': [],
 '35.2.217.12': [],
 '13.155.37.109': [],
 '186.57.89.102': [],
 '163.203.4.55': [],
 '99.225.208.87': [],
 '60.118.15.109': [],
 '193.120.191.19': [],
 '1.244.145.169': [],
 '143.31.77.82': [],
 '84.208.61.108': [],
 '19.5.254.189': [],
 '28.94.235.118': [],
 '132.127.103.143': [],
 '28.59.161.221': [],
 '76.51.194.173': [],
 '224.186.206.2': [],
 '163.106.78.209': [],
 '58.108.226.12': [],
 '131.158.187.240': [],
 '213.195.196.19': [],
 '206.85.18.215': [],
 '164.132.156.210': [],
 '11.225.193.38': [],
 '246.221.237.50': [],
 '22.144.58.74': [],
 '255.155.98.111': [],
 '20.151.150.135': [],
 '205.179.243.241': [],
 '237.189.166.140': [],
 '71.9.213.15': [],
 '94.3.89.238': [],
 '29.228.226.190': [],
 '173.201.206.34': [],
 '180.35.106.57': [],
 '118.177.142.119': [],
 '23.190.225.41': [],
 '166.60.154.162': [],
 '249.42.215.117': [],
 '235.198.244.167': [],
 '73.131.72.153': [],
 '24.224.224.187': [],
 '133.105.102.122': [],
 '230.100.85.23': [],
 '14.253.99.218': [],
 '188.103.53.27': [],
 '249.80.191.151': [],
 '69.44.242.217': [],
 '86.42.27.230': [],
 '39.126.138.170': [],
 '246.220.19.139': [],
 '209.194.131.249': [],
 '16.125.35.253': [],
 '42.86.26.60': [],
 '161.200.15.18': [],
 '30.24.215.27': [],
 '177.243.102.132': [],
 '161.250.230.198': [],
 '182.188.137.78': [],
 '12.204.56.74': [],
 '196.66.13.191': [],
 '211.187.192.64': [],
 '238.92.55.70': [],
 '242.164.22.57': [],
 '203.80.183.127': [],
 '180.39.185.234': [],
 '70.114.176.126': [],
 '149.154.34.224': [],
 '122.28.20.126': [],
 '24.198.193.220': [],
 '170.199.14.2': [],
 '44.73.74.86': [],
 '241.64.147.18': [],
 '249.36.61.134': [],
 '171.151.52.156': [],
 '243.39.217.227': [],
 '65.114.199.36': [],
 '131.105.229.56': [],
 '187.118.65.95': [],
 '230.115.237.188': [],
 '32.191.255.23': [],
 '236.138.2.58': [],
 '198.252.156.39': [],
 '104.110.99.92': [],
 '219.201.221.230': [],
 '25.10.13.84': [],
 '40.18.9.150': [],
 '154.19.90.105': [],
 '62.45.14.135': [],
 '61.160.215.139': [],
 '135.49.156.106': [],
 '74.200.214.162': [],
 '99.194.58.154': [],
 '179.138.114.226': [],
 '160.164.198.210': [],
 '12.72.242.47': [],
 '1.123.64.100': [],
 '190.229.192.10': [],
 '177.192.240.84': [],
 '31.72.22.53': [],
 '94.216.174.142': [],
 '63.129.182.41': [],
 '143.240.121.244': [],
 '97.234.222.47': [],
 '45.224.19.71': [],
 '128.103.253.159': [],
 '188.148.136.143': [],
 '93.195.24.109': [],
 '119.218.123.14': [],
 '64.132.103.114': [],
 '191.184.62.73': [],
 '227.109.167.87': [],
 '22.171.245.79': [],
 '84.127.169.219': [],
 '27.46.26.191': [],
 '134.109.122.137': [],
 '29.59.47.151': [],
 '28.72.47.231': [],
 '6.39.155.7': [],
 '76.162.137.59': [],
 '11.206.93.237': [],
 '107.99.127.122': [],
 '197.113.188.7': [],
 '2.80.180.49': [],
 '102.31.35.244': [],
 '152.219.105.160': [],
 '20.174.94.253': [],
 '126.110.195.14': [],
 '202.181.31.161': [],
 '188.138.19.225': [],
 '113.177.32.6': [],
 '158.140.34.140': [],
 '146.93.232.19': [],
 '246.191.148.196': [],
 '132.23.81.253': [],
 '59.132.53.134': [],
 '218.220.147.249': [],
 '221.169.154.21': [],
 '32.136.246.55': [],
 '64.212.59.155': [],
 '157.96.208.196': [],
 '201.59.188.71': [],
 '165.191.169.170': [],
 '223.40.27.55': [],
 '86.136.34.123': [],
 '120.192.237.160': [],
 '178.22.92.38': [],
 '19.205.245.20': [],
 '97.35.36.52': [],
 '177.145.90.202': [],
 '253.220.173.220': [],
 '146.90.71.207': [],
 '141.109.151.49': [],
 '32.36.94.189': [],
 '83.46.197.41': [],
 '110.201.229.121': [],
 '123.114.81.159': [],
 '114.128.109.77': [],
 '160.161.217.12': [],
 '11.191.19.2': [],
 '28.130.63.184': [],
 '84.107.112.84': [],
 '43.129.55.125': [],
 '175.72.119.160': [],
 '59.232.172.143': [],
 '232.93.89.145': [],
 '162.55.7.48': [],
 '31.220.255.137': [],
 '94.238.37.59': [],
 '173.67.221.237': [],
 '128.97.201.253': [],
 '17.76.155.46': [],
 '245.87.212.6': [],
 '72.225.185.32': [],
 '211.68.77.26': [],
 '44.78.20.81': [],
 '56.91.102.56': [],
 '4.110.5.128': [],
 '78.166.137.125': [],
 '204.50.38.52': [],
 '222.64.119.84': [],
 '179.144.41.109': [],
 '215.122.193.140': [],
 '189.174.11.177': [],
 '89.56.24.93': [],
 '210.184.107.177': [],
 '86.76.47.3': [],
 '15.140.92.143': [],
 '193.82.138.73': [],
 '221.107.187.116': [],
 '28.21.165.191': [],
 '197.246.153.123': [],
 '4.69.227.132': [],
 '43.216.171.187': [],
 '162.155.165.61': [],
 '110.7.224.128': [],
 '117.170.107.242': [],
 '163.170.246.248': [],
 '219.99.32.5': [],
 '78.27.89.134': [],
 '200.113.192.102': [],
 '181.93.83.54': [],
 '142.235.170.154': [],
 '210.133.6.38': [],
 '180.82.37.151': [],
 '252.151.67.31': [],
 '197.33.136.223': [],
 '73.193.105.168': [],
 '202.226.2.48': [],
 '23.177.254.136': [],
 '131.101.198.58': [],
 '68.2.15.116': [],
 '36.53.216.214': [],
 '26.169.86.86': [],
 '99.182.124.169': [],
 '239.162.155.67': [],
 '110.45.58.123': [],
 '31.221.55.127': [],
 '118.81.111.32': [],
 '232.174.146.151': [],
 '96.83.188.97': [],
 '159.102.177.36': [],
 '251.70.115.55': [],
 '102.224.15.189': [],
 '32.250.21.212': [],
 '99.184.254.212': [],
 '170.222.116.86': [],
 '234.197.196.211': [],
 '93.138.59.213': [],

In [ ]:
for i in range(len(df3)):
  if(df3['access_ip'].iloc[i] in unique_dict.keys()):
    key = df3['access_ip'].iloc[i]
    unique_dict[key].append(df3['item_name'].iloc[i])

In [ ]:
unique_dict

In [ ]:
data = pd.DataFrame.from_dict(unique_dict,orient = 'index')

In [ ]:
data

                                 0                         1   ...  27  28
188.244.165.181             VERSACE                   VERSACE  ... NaN NaN
210.54.66.88               GUCCI 남성  Web 디테일의 소프트 GG 수프림 더플 백  ... NaN NaN
62.47.31.96                 VERSACE                      None  ... NaN NaN
88.189.204.99                 CU상품권                   GoldBar  ... NaN NaN
95.90.201.200              GUCCI 남성             스몰 사이즈 십자가목걸이  ... NaN NaN
...                             ...                       ...  ...  ..  ..
154.80.80.221                  돔베고기               흑돼지 삼겹살 2kg  ... NaN NaN
247.186.92.198   [구찌 조던] 트위드 체크 로퍼                       None  ... NaN NaN
9.142.202.83                옥돔 30EA                      None  ... NaN NaN
244.243.51.184          흑돼지 삼겹살 1kg               흑돼지 오겹살 1kg  ... NaN NaN
86.247.246.59                 돌하루방떡                      무지개떡  ... NaN NaN

[51387 rows x 29 columns]

In [ ]:
df2['어리목'].tolist()

In [ ]:
df2['어리목'].values